### ISSUE TITLE
Kitkat problem

### ISSUE THREAD

**Issue by mircoker** [Joisar/LockScreenApp#8]
Application crashes when it starts.

01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime: FATAL EXCEPTION: main
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime: Process: com.mehuljoisar.lockscreen, PID: 18451
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime: java.lang.IllegalArgumentException: Window type can not be changed after the window is added.
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:1469)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.os.Parcel.readException(Parcel.java:1419)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.IWindowSession$Stub$Proxy.relayout(IWindowSession.java:835)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.ViewRootImpl.relayoutWindow(ViewRootImpl.java:5609)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1656)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1192)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6231)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:816)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.Choreographer.doCallbacks(Choreographer.java:619)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.Choreographer.doFrame(Choreographer.java:588)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:802)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:808)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:103)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:193)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5388)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:655)
01-04 18:06:21.096 18451-18451/com.mehuljoisar.lockscreen E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by jaytj95** [comment]
Bump. Same issue on 5.1.1

**Comment by ksv87** [comment]
move all from onAttachedToWindow to start of onCreate in LockScreenActivity.java

**Comment by AmoliShah** [comment]
Even after moving all from onAttachedToWindow to start of onCreate ,app get error as follows
FATAL EXCEPTION: main
                                                                                                                                             java.lang.IllegalArgumentException: Rect should intersect with child's bounds.
                                                                                 at android.support.design.widget.CoordinatorLayout.offsetChildByInset(CoordinatorLayout.java:1319)
                                                                                 at android.support.design.widget.CoordinatorLayout.onChildViewsChanged(CoordinatorLayout.java:1257)
                                                                                 at android.support.design.widget.CoordinatorLayout$OnPreDrawListener.onPreDraw(CoordinatorLayout.java:1805)
                                                                                 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:847)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1956)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5786)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5235)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
